@startuml
start
:Truy cập trang thông tin cá nhân;
:Ấn vào nút quên mật khẩu;

repeat
:Hiển thị form điền email;
:Điền email và ấn gửi;
repeat while(tài khoản chưa đăng ký) is (Đúng)
->Sai;
repeat
:Hiển thị form xác nhận;
:Lấy mã xác nhận, điền vào ô mã xác nhận và ấn nút “Gửi”;
repeat while(mã xác nhận không đúng, để trống) is (Đúng)
->Sai;
repeat
:Điều hướng đến trang đổi mật khẩu;
:Nhập thông tin mật khẩu và gửi;
repeat while(mật khẩu và nhập lại mật khẩu không khớp) is (Đúng)
->Sai;
:Trả về trang đăng nhập;
:Hiển thị lấy lại mật khẩu thành công;

stop
@enduml